name: LevelSystem
main: com.mauli.levelsystem.LevelSystemPlugin
version: 1.0.0
api-version: '1.20'
authors: [ 'MauliCraft' ]
commands:
  level:
    description: Öffnet das Level-Interface
    usage: /level
  leveladmin:
    description: Admin-Tools
    usage: /leveladmin <reload|addvotes|open|resetclaim>
permissions:
  levelsystem.admin:
    default: op
