name: LevelSystem
main: com.mauli.levelsystem.LevelSystemPlugin
version: 1.0.0
api-version: '1.21'
commands:
  level:
    description: Öffnet das Level-Menü
    usage: /level
  leveladmin:
    description: Admin-Befehle fürs Levelsystem
    usage: /leveladmin
permissions:
  levelsystem.admin:
    default: op
