name: MauliLevelSystem
main: com.mauli.levelsystem.LevelSystemPlugin
version: 1.0.0
api-version: '1.20'
softdepend: [Votifier, VotingPlugin]
commands:
  level:
    description: Öffnet das Level-Menü
    usage: /level
  leveladmin:
    description: Admin-Befehle
    usage: /leveladmin <reload|setminutes|setvotes|resetclaims>
permissions:
  levelsystem.admin:
    default: op
