name: LevelSystem
main: com.mauli.levelsystem.LevelSystemPlugin
version: 1.0.0
api-version: '1.21'

commands:
  level:
    description: Öffnet das Level GUI
    usage: /level
  leveladmin:
    description: Admin-Befehle für LevelSystem
    usage: /leveladmin <reload|reset <Spieler>>

permissions:
  levelsystem.admin:
    default: op
